# Generated by Django 4.0 on 2022-06-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My project', max_length=50)),
                ('blurb', models.CharField(default='Check out my project!', max_length=100)),
                ('description', models.TextField(default="I haven't written my project description yet, but trust me it will be awesome!")),
                ('UserString', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('classes', models.ManyToManyField(blank=True, related_name='profiles', to='classroom.Classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
