# Generated by Django 4.0 on 2022-06-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forum', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My project', max_length=50)),
                ('blurb', models.CharField(default='Check out my project!', max_length=100)),
                ('description', models.TextField(default="I haven't written my project description yet, but trust me it will be awesome!")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=0)),
                ('stars', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('classes', models.ManyToManyField(blank=True, default=None, related_name='profiles', to='classroom.Classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.comment')),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_notifications', to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.project'),
        ),
        migrations.CreateModel(
            name='AnswerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.answer')),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_notifications', to='auth.user')),
            ],
        ),
    ]
