# Generated by Django 4.0 on 2022-06-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='UserString',
            new_name='user',
        ),
    ]
