# Generated by Django 4.0 on 2022-06-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_answernotification_delete_questionnotification'),
        ('users', '0009_rename_comment_projectcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.question')),
                ('comment', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.projectcomment')),
            ],
        ),
    ]
