# Generated by Django 4.0 on 2022-06-16 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_answernotification_delete_questionnotification'),
        ('users', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='answer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.answer'),
        ),
    ]
