# Generated by Django 4.0 on 2022-06-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0011_alter_notification_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='ProjectCommentNotification',
            new_name='CommentNotification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
