# Generated by Django 4.0 on 2022-06-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_delete_answernotification'),
        ('users', '0012_rename_projectcomment_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.answer')),
            ],
        ),
    ]
