# Generated by Django 4.0 on 2022-06-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_commentnotification_answernotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answernotification',
            old_name='user',
            new_name='notified_user',
        ),
        migrations.RenameField(
            model_name='commentnotification',
            old_name='user',
            new_name='notified_user',
        ),
    ]
