# Generated by Django 4.0 on 2022-06-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
