# Generated by Django 4.0 on 2022-06-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
