# Generated by Django 4.0 on 2022-06-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Classroom', max_length=50)),
                ('year', models.IntegerField(default=1900)),
                ('join_code', models.CharField(default='abc123', max_length=10)),
            ],
        ),
    ]
